services:
  web_server:
    build: .
    ports:
      - "5000"
    volumes:
      - .:/my_code

  nginx_lb:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    container_name:  nginx_lb
    depends_on: 
      - web_server
